### ISSUE TITLE
BoxEdit Fails

### ISSUE THREAD

**Issue by jonbrown21** [autopkg/joshua-d-miller-recipes#47] opened 2018-08-08 02:08 UTC
Not sure if they are changing how they distribute this or not. I went to download manually and could only get the downloader installer for all their tools. 

```
BoxEdit.munki.recipe...
Curl failure: The requested URL returned error: 403 Forbidden (exit code 22)
Failed.
```

**Comment by MattRK** [comment] 2018-08-28 20:38
Confirming that this recipe fails. Looks like there may be a couple of separate issues. I noticed that the CFBundleShortVersionString for the Box Device Trust app in the installs array is incorrect. I updated it manually and it still fails. I then checked the logs and it seems to point at a problem with the pre_install script. Here is the error from my logs:

> Aug 28 2018 15:20:34 -0500 ### Beginning managed installer session ###
Aug 28 2018 15:20:34 -0500 Processing installs
Aug 28 2018 15:20:34 -0500     Running preinstall_script for Box Edit
Aug 28 2018 15:20:34 -0500     Plugin Not Present.  Continuing...
Aug 28 2018 15:20:34 -0500     Old Version not present.  Continuing...
Aug 28 2018 15:20:34 -0500       609 ??         0:09.31 /Users/mkeller/Library/Application Support/Box/Box Edit/Box Edit.app/Contents/PlugIns/BoxEditFinderExtension.appex/Contents/MacOS/BoxEditFinderExtension
Aug 28 2018 15:20:34 -0500     79509 ??         0:00.54 /Library/Application Support/Box/Box Edit/Box Edit.app/Contents/PlugIns/BoxEditFinderExtension.appex/Contents/MacOS/BoxEditFinderExtension
Aug 28 2018 15:20:34 -0500     88442 ??         0:00.24 /Library/Application Support/Box/Box Edit/Box Edit.app/Contents/PlugIns/BoxEditFinderExtension.appex/Contents/MacOS/BoxEditFinderExtension
Aug 28 2018 15:20:34 -0500     No matching processes were found
Aug 28 2018 15:20:34 -0500     No matching processes were found
Aug 28 2018 15:20:34 -0500 ERROR: Running preinstall_script for Box Edit failed.
Aug 28 2018 15:20:34 -0500 ERROR: ------------------------------------------------------------------------------
Aug 28 2018 15:20:34 -0500 ERROR: 	Plugin Not Present.  Continuing...
Aug 28 2018 15:20:34 -0500 ERROR: 	Old Version not present.  Continuing...
Aug 28 2018 15:20:34 -0500 ERROR: 	  609 ??         0:09.31 /Users/mkeller/Library/Application Support/Box/Box Edit/Box Edit.app/Contents/PlugIns/BoxEditFinderExtension.appex/Contents/MacOS/BoxEditFinderExtension
Aug 28 2018 15:20:34 -0500 ERROR: 	79509 ??         0:00.54 /Library/Application Support/Box/Box Edit/Box Edit.app/Contents/PlugIns/BoxEditFinderExtension.appex/Contents/MacOS/BoxEditFinderExtension
Aug 28 2018 15:20:34 -0500 ERROR: 	88442 ??         0:00.24 /Library/Application Support/Box/Box Edit/Box Edit.app/Contents/PlugIns/BoxEditFinderExtension.appex/Contents/MacOS/BoxEditFinderExtension
Aug 28 2018 15:20:34 -0500 ERROR: 	No matching processes were found
Aug 28 2018 15:20:34 -0500 ERROR: 	No matching processes were found
Aug 28 2018 15:20:34 -0500 ERROR: ------------------------------------------------------------------------------
Aug 28 2018 15:20:34 -0500 ###    End managed installer session    ###

**Comment by MattRK** [comment] 2018-08-29 15:50
I just realized that my above comment was not the same issue as OP... though it might be related. My issue is the software not *installing*. The recipe runs fine and downloads the software for me. The issue we have is that the Munki can't install the software. Sorry for the confusion. I can start a separate issue if needed.

**Comment by joshua-d-miller** [comment] 2019-11-08 13:11
I realize it's been a while but is anyone still using Box Edit at this point since the release of Box Drive? It seems like Sync and Edit are disappearing and Drive is the way to go. Just curious

**Comment by joshua-d-miller** [comment] 2021-05-12 10:43
Hello all,

Please try @macmule's latest changes to Box Edit and see if this now works as intended.

**Comment by joshua-d-miller** [comment] 2021-09-08 09:53
As I have not heard anything, I'm going to go ahead and close this issue. If there are any further issues please let me know.

**Closed by joshua-d-miller** 2021-09-08 09:53 UTC
